### PR TITLE
ability to specify background color as option

### LINKED ISSUE #10: Feature Request: Dynamic background color
Is there a way to override the background color using a data attribute?

### PR DESCRIPTION
**Pull request by Yaroslav-F**
Now you can specify background color as an option in constructor or data attribute. Fixes #10 .

### CODE REVIEW

**Comment by saygun** [comment]
any update on this?

**Comment by ola-rende** [comment]
@judesfernando You should strongly consider merging this.

**Comment by saygun** [comment]
@judesfernando I agree with @ola-rende

**Comment by Yaroslav-F** [comment]
Updated PR with newest master branch commits to resolve the merging conflicts.

**Comment by judesfernando** [comment]
Thank you!

**Comment by dgilperez** [comment]
Could you release a new version with this change? I'd like to update the [Rails wrapper gem](https://github.com/dgilperez/initialjs-rails) version accordinglu with this change as we're using this in a couple of projects.

**Pull request merged**
